//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFarmapro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int ID_DETALLE_FACTURA { get; set; }
        public int ID_FACTURA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO_UNIDAD { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
